version: 2
registries:
  rubygems-server-novullc-jfrog-io-novullc-api-gems-dev-gems-relea:
    type: rubygems-server
    url: https://novullc.jfrog.io/novullc/api/gems/dev-gems-release-virtual/
    username: "${{secrets.RUBYGEMS_SERVER_NOVULLC_JFROG_IO_NOVULLC_API_GEMS_DEV_GEMS_RELEA_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_NOVULLC_JFROG_IO_NOVULLC_API_GEMS_DEV_GEMS_RELEA_PASSWORD}}"
  docker-registry-822373129316-dkr-ecr-us-east-1-amazonaws-com:
    type: docker-registry
    url: https://822373129316.dkr.ecr.us-east-1.amazonaws.com
    username: AKIA366KCDRSGVMJOHEX
    password: "${{secrets.DOCKER_REGISTRY_822373129316_DKR_ECR_US_EAST_1_AMAZONAWS_COM_PASSWORD}}"
  rubygems-server-enterprise-contribsys-com:
    type: rubygems-server
    url: https://enterprise.contribsys.com
    username: "${{secrets.RUBYGEMS_SERVER_ENTERPRISE_CONTRIBSYS_COM_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_ENTERPRISE_CONTRIBSYS_COM_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  registries:
  - rubygems-server-novullc-jfrog-io-novullc-api-gems-dev-gems-relea
  - rubygems-server-enterprise-contribsys-com
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine
  registries:
  - docker-registry-822373129316-dkr-ecr-us-east-1-amazonaws-com
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@rails/webpacker"
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: jquery
    versions:
    - 3.5.1
